---
bibliography: Bibliografie.bib
csl: iso690-author-date-cs.csl
fig_caption: yes
fontsize: 12pt
geometry: left=4cm,right=2.5cm,top=2.5cm,bottom=2.5cm
header-includes: \usepackage[czech]{babel} 
                 \usepackage{docmute} 
                 \usepackage{float}
                 \usepackage{pdfpages} 
                 \usepackage{bm} 
                 \setcounter{tocdepth}{4}
                 \usepackage{graphicx} 
                 \usepackage{array} 
                 \usepackage{wrapfig} 
                 \usepackage{subcaption}
                 \usepackage{siunitx}
                 \usepackage{csquotes}
                 \MakeOuterQuote{"}
                 \usepackage{natbib}
                 \usepackage{hyperref}
                 

                 
output:
  pdf_document: 
    keep_tex: yes
---

```{r setup, include=FALSE, cache = TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
require("ggplot2") 
require("markdown")
require("knitr")
require("plotrix")
set.seed(666)
x <- rnorm(100, 0, 1)
```

\input{Tit_list.tex}

\tableofcontents

\newpage

\listoffigures
\listoftables

\newpage

```{r, child = 'Chapter_0.Rmd'}
```

\newpage

```{r, child = 'Chapter_1.Rmd'}
```


```{r, child = 'Chapter_2.Rmd'}
```

\newpage

```{r, child = 'Chapter_3.Rmd'}
```

\newpage

```{r, child = 'Chapter_4.Rmd'}
```


```{r, child = 'Chapter_5.Rmd'}
```

\newpage

```{r, child = 'Chapter_6.Rmd'}
```

\newpage

# Literatura
\label{literatura}

<div id="refs"></div>

\newpage

\section*{Poznamky}

 \thispagestyle{empty}
 
[@minard1858] [@palsky1996]
