---
output:
  word_document: default
  html_document: default
---

# Výsledky {-}

\qquad Výsledkem práce je shrnutí klíčových poznatků týkajících se vizualizace a průzkumové analýzy dat s jejich následnou praktickou implementaci v R, a to v podobě webové interaktivní aplikace. Aplikace slouží k analýze hydrologické bilance a předpovědi sucha v útvarech povrchových vod České republiky. Hlavní funkcionalita aplikace spočívá v její interaktivitě. Uživatel má možnost si prohlédnout data v různých reprezentacích, a to například prostorové rozložení prvků hydrologické bilance na území ČR, jejich časové řady, čáry překročení pro jednotlivé útvary či plošné rozložení indikátorů sucha. Díky tomu si uživatel může snadno vyhledat potřebné informace pro další analýzu a případný návrh řešení problematiky sucha. Možnosti vlastního průzkumu dat, bez potřeby znalosti programovacího jazyka, případně struktury souborů, v rámci přehledné interaktivní aplikace je jedním z hlavních přínosu této práce. 

\qquad Aplikace je dostupná v digitální podobě jak na přiloženým datovém nosiči, tak i&nbsp;na [serveru fakulty](https://shiny.fzp.czu.cz/KVHEM/HAMR/)^[Aplikace na serveru fakulty: https://shiny.fzp.czu.cz/KVHEM/HAMR/] (viz kapitola [5.1](#techres)). Složky a soubory datového nosiče jsou popsány v kapitole [5.2](#data) a přehled jejich struktury je znázorněn na obrázku \ref{fig:ch5.1}.

\newpage

# Diskuse {#diskuse}

\qquad Přestože aplikace je plně funkční, existuje prostor k jejímu vylepšení a odladění nedostatků. Současná verze aplikace stále obsahuje drobné chyby. Většina těchto chyb je způsobena chybami v používaných balíčcích, jelikož jsou stále ve vývoji. Celkově je to nedostatek R, které je distribuováno pod všeobecnou veřejnou licencí GNU GPL (*General Public License*) a neposkytuje absolutně žádné záruky. Obdobně i většina balíčků neposkytuje záruky, ani uživatelskou podporu. Z tohoto důvodu pro aplikaci byly zvoleny balíčky, které jsou stále aktivně vyvíjeny, chyby jsou postupně odstraňovány a lze je vývojářům nahlásit (například pomocí GitHub). Pro ostré nasazení systému (které se výhledově ze strany Ministerstva životního prostředí předpokládá) bude pravděpodobně nezbytné aplikaci přepsat do prostředí umožňujícího rychlou vizualizaci komplexních geodat a dlouhých časových řad a&nbsp;zároveň zvládajícího vysokou návštěvnost uživatelů. Možností může být buď placená verze Shiny serveru nebo platforma typu [GISQUICK](http://gisquick.org/)^[GISQUICK je open source platformou pro publikování geoprostorových dat, viz http://gisquick.org/.].

\qquad Další problém se kterým se R potýká je reprodukovatelnost výsledků. S každou aktualizaci R a balíčků hrozí totiž ztráta plné kompatibility. Pro finální verzí aplikace bude nutné se s tímto problémem vypořádat. V současnosti existuje několik řešení, jako je například balíček `checkpoint`, případně balíček `packrat`. 

\qquad První načtení aplikace trvá přibližně 40 vteřin^[Měřeno na osobním počítači s konfigurací: i5-5200U, 8GB RAM, SSD.] a přepínání mezi jednotlivými záložkami není okamžité. Lepšího výsledků by mohlo být dosaženo pomocí načítání dat z databáze typu `PostgreSQL`, `mongoDB` či jiného systému s rozhraním pro R&nbsp;(prostřednictvím balíčků `DBI` a `dbplyr`). Tento přechod by avšak potřeboval odporných znalostí a měl by být důkladně zvážen před bezprostřední implementací. Problém rychlostí aplikace by mohlo také vyřešit její rozdělení do jednotlivých menších aplikací, tento krok avšak vyvolává otázky o přehledností tohoto přístupu a komfortu uživatele. 

\newpage

# Závěr {-} 

\qquad V teoretické části je popsána historie a zásady vizualizace, průzkumová analýza dat, základní a pokročilé vizualizační nástroje v R. Na základě teoretické části je následně vytvořená interaktivní webová aplikace pro analýzu hydrologické bilance a předpověď sucha v útvarech povrchových vod ČR. Struktura a konkrétní řešení aplikace jsou podrobně popsány v praktické části. Tato aplikace umožňuje uživateli průzkum dat hydrologické bilance, časových řad prvků hydrologické bilance a jejich čar překročení, plošné rozložení indikátorů sucha, míst užívání vod a informaci o&nbsp;odběratelích atd. Všechny tyto informace jsou v rámci aplikace přehledně prezentovány a grafy jsou vytvořeny v souladu se zásadami vizualizace dat. 

\qquad Možné nedostatky jsou zmíněny v sekci ["Diskuse"](#diskuse) a zároveň jsou předložena jejich možná řešení. Aplikace je v současné verzi plně funkční a připravená k používání. Další vývoj bude podmíněn požadavky zadavatele a uživatelů. Základní kostra aplikace umožňuje snadné rozšíření o další záložky a implementace nových funkcí nepředstavuje žádný problém. 

