---
output:
  word_document: default
  html_document: default
---
# Úvod
\pagestyle{plain}
\setcounter{page}{1}

\qquad Vizualizace dat vždy hrála významnou roli v datové analýze. Je to jeden z nejlepších a nejjednodušších (nejpřímějších?) způsobů pro pochopení a prezentaci dat. Vizualizace poskytuje jasnou představu o složení dat, odhaluje skryté struktury v datech a shrnuje informace. Proces vizualizací je nedílnou součásti mnoha analýz a téměř všechna odvětví využívají grafického zobrazení dat k vizualizaci a komunikaci svých výsledků.

\qquad Data z těchto odvětví, která jsou sbírána a analyzována po dobu mnoha let se čím dat častěji převádějí do grafické formy. Masivní příliv dat a jejich dostupnost vedly k novým metodám a novým přístupům. Kombinace programovacích dovedností, matematických a statistických znalostí a jiných odborných znalostí týkajících se obsahu přijala název "*Data Science*" [@datavis_rahlf]. V oblasti environmentálních dat to znamená možnost modelování klimatických změn a odhalení ekologických rizik s následným tlumočením výsledků široké veřejností.

\qquad Hlavní výhodou vizualizace je její relativní jednoduchost na zpracování a dostupnost různých nástrojů k její tvorbě. Avšak nesprávné či nevhodné použití těchto nástrojů vede k existenci grafů, které lze považovat za nepřehledné, postrádající smysl až zavádějící. Z tohoto důvodů je vhodné se obracet na takzvané zásady vizualizace.

\qquad Táto bakalářská práce se zabývá shrnutím klíčových poznatků o vizualizaci a průzkumové analýze dat, a to jak z teoretického hlediska, tak i z hlediska praktické implementace v programovacím jazyku R.  Budou popsány zásady vizualizace, její zařazení do datové analýzy, moderní způsoby vizualizace a pokročilé R baličky. Součásti práce je také webová aplikace pro vizualizaci a analýzu hydrologické bilance a předpověď sucha v útvarech povrchových vod ČR.

\newpage

# Cíle práce

\qquad Práce má dva hlavní cíle. Prvním cílem se zabývá teoretická část, která shrnuje klíčové poznatky týkajících se zásad vizualizace, průzkumové analýzy dat a vizualizace v statistickém programovacím jazyku R. Nejdříve je popsána krátká historie vizualizace, výsledkem které bylo stanovení jejích zásad. Vývoj vizualizace je těsně propojen s vývojem statistiky a výpočetní techniky, což se projevilo na vývoji analýzy dat. Postupně se vizualizace stala jedním z klíčových nástrojů průzkumové analýzy, která využívá statistické grafy a modelování k lepšímu pochopení dat. Dále teoretická část obsahuje informace o nástrojích současné vizualizace dat v jazyku R, který je v současnosti jeden z nejpopulárnějších nástrojů analýzy dat [@stackover]. Popsány jsou jak základní možností, tak i nejčastěji používané balíčky. Další cíl této bakalářské práce staví na teoretické částí a využívá informace v ní obsažené k vytvoření webové aplikace s interaktivními prvky pro demonstraci možností moderní vizualizace enviromentálních dat. 

